apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/installs/generic
  - ../../base/metadata/base
  - ../../third-party/argo/installs/namespace
#  - ../../third-party/minio/base
#  - ../../third-party/mysql/base
  - ../../third-party/cloudties/minio
  - ../../third-party/cloudties/mysql
  - ../../third-party/cloudties/mlflow/base
#  - ../../third-party/cloudties/katib/katib-crds/base
#  - ../../third-party/cloudties/katib/katib-controller/base
  - ../../third-party/grafana
  - ../../third-party/prometheus

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines

# !!! If you want to customize the namespace,
# please also update base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
namespace: kubeflow
